package ni.gob.minsa.myapplication.composables.home

import androidx.compose.animation.AnimatedContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.consumeWindowInsets
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedCard
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.contentColorFor
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import ni.gob.minsa.myapplication.data.TaskRepository
import ni.gob.minsa.myapplication.model.Task
import ni.gob.minsa.myapplication.model.TaskStatus


@Composable
fun HomeScreen(
    onCreateTask: () -> Unit,
    onOpenTask: (Task) -> Unit,
    modifier: Modifier = Modifier,
    viewModel: HomeViewModel = viewModel { HomeViewModel(TaskRepository) }
) {
    val tasks by viewModel.tasks.collectAsStateWithLifecycle()

    Scaffold(
        modifier = modifier,
        topBar = { TopAppBar(title = { Text("Tasks") }) },
        floatingActionButton = {
            FloatingActionButton(onClick = onCreateTask) {
                Icon(Icons.Default.Add, contentDescription = "Add Task")
            }
        }
    ) {
        AnimatedContent(tasks.isNotEmpty()) { isNotEmpty ->
            if (isNotEmpty) {
                LazyColumn(
                    modifier = Modifier
                        .padding(it)
                        .consumeWindowInsets(it)
                        .fillMaxSize(),
                    contentPadding = PaddingValues(all = 16.dp),
                    verticalArrangement = Arrangement.spacedBy(16.dp)
                ) {
                    items(tasks) { task ->
                        TaskItem(
                            modifier = Modifier.fillParentMaxWidth(),
                            task = task,
                            onClick = { onOpenTask(task) }
                        )
                    }
                }
            } else {
                Box(
                    modifier = Modifier
                        .padding(it)
                        .consumeWindowInsets(it)
                        .fillMaxSize()
                        .padding(16.dp),
                    contentAlignment = Alignment.Center
                ) {
                    Text("No tasks yet. Tap + to create one.")
                }
            }
        }
    }
}

@Composable
fun TaskItem(modifier: Modifier, task: Task, onClick: () -> Unit) {
    OutlinedCard(modifier = modifier, onClick = onClick) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text(
                text = task.title,
                style = MaterialTheme.typography.titleMedium,
                maxLines = 1,
                softWrap = true,
                overflow = TextOverflow.Ellipsis
            )
            Text(
                text = task.description,
                style = MaterialTheme.typography.bodyMedium,
                maxLines = 2,
                softWrap = true,
                overflow = TextOverflow.Ellipsis
            )

            Box(
                modifier = Modifier
                    .padding(top = 8.dp)
                    .background(task.status.color, shape = RoundedCornerShape(10.dp))
                    .padding(horizontal = 8.dp, vertical = 4.dp)
            ) {
                Text(
                    text = task.status.displayName,
                    style = MaterialTheme.typography.labelMedium,
                    maxLines = 1,
                    softWrap = true,
                    overflow = TextOverflow.Ellipsis,
                    color = contentColorFor(task.status.color)
                )
            }
        }
    }
}

/**
 * Auto-generated by Compose Preview Generator.
 * Upgrade your license to remove auto-generated comments.
 * https://plugins.jetbrains.com/plugin/25716-compose-preview-generator
 */
@Preview
@Composable
private fun HomeScreenPreview() {
    HomeScreen(
        onCreateTask = {},
        onOpenTask = {},
        viewModel = HomeViewModel(TaskRepository)
    )
}
/**
 * Auto-generated by Compose Preview Generator.
 * Upgrade your license to remove auto-generated comments.
 * https://plugins.jetbrains.com/plugin/25716-compose-preview-generator
 */

/**
 * Auto-generated by Compose Preview Generator.
 * Upgrade your license to remove auto-generated comments.
 * https://plugins.jetbrains.com/plugin/25716-compose-preview-generator
 */
@Preview
@Composable
private fun TaskItemPreview() {
    TaskItem(
        modifier = Modifier,
        task = Task(
            0L, "Preview", "Preview", TaskStatus.ToDo, 0L, 0L
        ),
        onClick = {}
    )
}
/**
 * Auto-generated by Compose Preview Generator.
 * Upgrade your license to remove auto-generated comments.
 * https://plugins.jetbrains.com/plugin/25716-compose-preview-generator
 */

